///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CommentEntity {
/*
{
  "postId": 1,
  "id": 1,
  "name": "id labore ex et quam laborum",
  "email": "Eliseo@gardner.biz",
  "body": "laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium"
} 
*/

  int? postId;
  int? id;
  String? name;
  String? email;
  String? body;

  CommentEntity({
    this.postId,
    this.id,
    this.name,
    this.email,
    this.body,
  });
  CommentEntity.fromJson(Map<String, dynamic> json) {
    postId = json['postId']?.toInt();
    id = json['id']?.toInt();
    name = json['name']?.toString();
    email = json['email']?.toString();
    body = json['body']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['postId'] = postId;
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['body'] = body;
    return data;
  }
}
