import 'package:flutter/material.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class JobEntity {
/*
{
  "title": "Recon flight",
  "id": "500px175207523",
  "choosed": false,
  "logo": "",
  "time": "",
  "address": "",
  "price": "",
  "url": ""
} 
*/

  String? title;
  String? id;
  bool? choosed;
  IconData? logo;
  String? time;
  String? address;
  String? price;
  String? url;

  JobEntity({
    this.title,
    this.id,
    this.choosed,
    this.logo,
    this.time,
    this.address,
    this.price,
    this.url,
  });
  JobEntity.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    id = json['id']?.toString();
    choosed = json['choosed'];
    logo = json['logo'];
    time = json['time']?.toString();
    address = json['address']?.toString();
    price = json['price']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['id'] = id;
    data['choosed'] = choosed;
    data['logo'] = logo;
    data['time'] = time;
    data['address'] = address;
    data['price'] = price;
    data['url'] = url;
    return data;
  }
}
