///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PhotoEntityUrl {
/*
{
  "p1": "https://img.500px.me/500px175207523.jpg!p1",
  "p2": "https://img.500px.me/500px175207523.jpg!p2",
  "baseUrl": "https://img.500px.me/500px175207523.jpg",
  "p3": "https://img.500px.me/500px175207523.jpg!p3",
  "p4": "https://img.500px.me/500px175207523.jpg!p4",
  "id": "500px175207523"
} 
*/

  String? p1;
  String? p2;
  String? baseUrl;
  String? p3;
  String? p4;
  String? id;

  PhotoEntityUrl({
    this.p1,
    this.p2,
    this.baseUrl,
    this.p3,
    this.p4,
    this.id,
  });
  PhotoEntityUrl.fromJson(Map<String, dynamic> json) {
    p1 = json['p1']?.toString();
    p2 = json['p2']?.toString();
    baseUrl = json['baseUrl']?.toString();
    p3 = json['p3']?.toString();
    p4 = json['p4']?.toString();
    id = json['id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['p1'] = p1;
    data['p2'] = p2;
    data['baseUrl'] = baseUrl;
    data['p3'] = p3;
    data['p4'] = p4;
    data['id'] = id;
    return data;
  }
}

class PhotoEntity {
/*
{
  "title": "Recon flight",
  "id": "500px175207523",
  "state": 0,
  "height": 1365,
  "url": {
    "p1": "https://img.500px.me/500px175207523.jpg!p1",
    "p2": "https://img.500px.me/500px175207523.jpg!p2",
    "baseUrl": "https://img.500px.me/500px175207523.jpg",
    "p3": "https://img.500px.me/500px175207523.jpg!p3",
    "p4": "https://img.500px.me/500px175207523.jpg!p4",
    "id": "500px175207523"
  },
  "commentCount": 0,
  "pictureLikeedCount": 0,
  "width": 2048,
  "categoryId": "9",
  "resourceType": 0
} 
*/

  String? title;
  String? id;
  int? state;
  int? height;
  PhotoEntityUrl? url;
  int? commentCount;
  int? pictureLikeedCount;
  int? width;
  String? categoryId;
  int? resourceType;

  PhotoEntity({
    this.title,
    this.id,
    this.state,
    this.height,
    this.url,
    this.commentCount,
    this.pictureLikeedCount,
    this.width,
    this.categoryId,
    this.resourceType,
  });
  PhotoEntity.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    id = json['id']?.toString();
    state = json['state']?.toInt();
    height = json['height']?.toInt();
    url = (json['url'] != null) ? PhotoEntityUrl.fromJson(json['url']) : null;
    commentCount = json['commentCount']?.toInt();
    pictureLikeedCount = json['pictureLikeedCount']?.toInt();
    width = json['width']?.toInt();
    categoryId = json['categoryId']?.toString();
    resourceType = json['resourceType']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['id'] = id;
    data['state'] = state;
    data['height'] = height;
    if (url != null) {
      data['url'] = url!.toJson();
    }
    data['commentCount'] = commentCount;
    data['pictureLikeedCount'] = pictureLikeedCount;
    data['width'] = width;
    data['categoryId'] = categoryId;
    data['resourceType'] = resourceType;
    return data;
  }
}
