// ignore_for_file: constant_identifier_names

import 'keys.dart';

const Map<String, String> en_US = {
  Languages.chinese: 'Chinese',
  Languages.english: 'English',
  Languages.cancel: 'Cancel',
  Languages.done: 'Done',
  Languages.splashbutton: 'Get Started',
  Languages.loadingDefaultStatus: 'Loading',
  Languages.loadingEmpty: 'Oh, it`s empty, what can I do?',
  Languages.loadingError: 'Oh, it`s error, help me!',
  Languages.loadingRetry: 'Try Again',
  Languages.dragText: 'Pull to refresh',
  Languages.armedText: 'Release ready',
  Languages.readyText: 'Refreshing...',
  Languages.processingText: 'Refreshing...',
  Languages.processedText: 'Succeeded',
  Languages.failedText: 'Failed',
  Languages.noMoreText: 'No more',
  Languages.dragTextLoad: 'Pull to load',
  Languages.armedTextLoad: 'Release ready',
  Languages.readyTextLoad: 'Loading...',
  Languages.processingTextLoad: 'Loading...',
  Languages.processedTextLoad: 'Succeeded',
  Languages.failedTextLoad: 'Failed',
  Languages.noMoreTextLoad: 'No more',
  Languages.tabbarhome: 'Home',
  Languages.tabbarmine: 'Mine',
  Languages.signin: 'Get Started',
  Languages.signup: 'Sign Up',
  Languages.signout: 'Sign Out',
  Languages.signinmessage: 'We are here to make your holiday easier',
  Languages.signinnoaccount: 'Do not have a account? ',
  Languages.signupmessage: 'Put your account ',
  Languages.accounthint: 'account',
  Languages.pwdhint: 'password',
  Languages.home: 'Home',
  Languages.mine: 'Mine',
  Languages.setting: 'Setting',
  Languages.themechange: 'Theme',
  Languages.themechangedark: 'Dark Mode',
  Languages.themechangelight: 'Light Mode',
  Languages.themechangesys: 'System Mode',
  Languages.languagechange: 'Language',
  Languages.languagechangecn: 'Chinese',
  Languages.languagechangeen: 'English',
};
