// ignore_for_file: constant_identifier_names

import 'keys.dart';

const Map<String, String> zh_CN = {
  Languages.chinese: '中文',
  Languages.english: '英语',
  Languages.cancel: '取消',
  Languages.done: '确定',
  Languages.splashbutton: '直接进入',
  Languages.loadingDefaultStatus: '加载中',
  Languages.loadingEmpty: '暂无数据~',
  Languages.loadingError: '出错了~',
  Languages.loadingRetry: '重试一次',
  Languages.dragText: '下拉开始刷新',
  Languages.armedText: '松开刷新',
  Languages.readyText: '正在刷新',
  Languages.processingText: '正在刷新',
  Languages.processedText: '刷新完成',
  Languages.failedText: '刷新失败',
  Languages.noMoreText: '已显示全部数据',
  Languages.dragTextLoad: '上拉加载更多',
  Languages.armedTextLoad: '松开加载',
  Languages.readyTextLoad: '正在加载',
  Languages.processingTextLoad: '正在加载',
  Languages.processedTextLoad: '加载完成',
  Languages.failedTextLoad: '加载失败',
  Languages.noMoreTextLoad: '已显示全部数据',
  Languages.tabbarhome: '首页',
  Languages.tabbarmine: '我的',
  Languages.signin: '登 录',
  Languages.signup: '注 册',
  Languages.signout: '退出登录',
  Languages.signinmessage: '我们将为您打造一个快乐的假期，尽情放松吧！',
  Languages.signinnoaccount: '没有账号? ',
  Languages.signupmessage: '请输入账号',
  Languages.accounthint: '账号',
  Languages.pwdhint: '密码',
  Languages.home: '首页',
  Languages.mine: '我的',
  Languages.setting: '设置',
  Languages.themechange: '主题',
  Languages.themechangedark: '深色模式',
  Languages.themechangelight: '普通模式',
  Languages.themechangesys: '跟随系统',
  Languages.languagechange: '语言',
  Languages.languagechangecn: '中文',
  Languages.languagechangeen: '英语',
};
